# Site settings
title: Summernote - Super Simple WYSIWYG editor
email: summernoteis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Super Simple WYSIWYG Editor on Bootstrap
  Summernote is a JavaScript library that helps you create WYSIWYG editors online.
author: https://github.com/summernote
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://summernote.org" # the base hostname & protocol for your site
github_username: summernote

# Summernote settings
version: 0.8.18
repository: "https://github.com/summernote/summernote"
jquery_js: "https://code.jquery.com/jquery-3.5.1.min.js"
bootstrap_css: "https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
bootstrap_js: "https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
summernote_css: "https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css"
summernote_js: "https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"

# Build settings
markdown: kramdown

plugins_dir:
  - jekyll-sitemap
